# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5b2fb962597e680e4aeb4bd7ed92b1f578cae526e509b5e4682ea73f460d7105360b725fa1517f754df25cf04c4d24fb9992795e591cda9ef947b9a5d49243

test:
  secret_key_base: 6b675c342f284b958f848bc64054fc86bdb7861051a909b19b9f328481f5a385b3621f5ac207920c2ba6a39def56eff1b7b2792a04f02d01b1fa415b455b6aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
